packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  "@types/node": ^24
  "@types/three": ^0.174
  immer: ^10
  three: ^0.174
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  zustand: ^5.0.12

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
