packages:
  - apps/*
  - packages/*
  - tools/*
allowBuilds:
  esbuild: true
  protobufjs: true
  sharp: true

catalog:
  "@google/genai": ^1.46.0
  "@types/mime": ^4.0.0
  "@types/node": ^24
  "@types/three": ^0.174
  immer: ^10
  lil-gui: ^0.21.0
  mime: ^4.1.0
  sharp: ^0.34.5
  simplex-noise: ^4.0.3
  three: ^0.174
  tsx: ^4.21.0
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  zustand: ^5.0.12

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
