import type { TileFlags } from "./tile-data.js";
import { TileFlag } from "./tile-data.js";

export interface StaticTileDef {
  staticId: string;
  name: string;
  category: "tree" | "rock" | "structure" | "decoration" | "fishing" | "wall" | "fence";
  flags: TileFlags;
  sprite: string | null;
  width: number;
  height: number;
  renderHeight: number;
  fallbackColor: number;
}

export const STATIC_TILES: Record<string, StaticTileDef> = {
  // ---- Trees ----
  "normal-tree": {
    staticId: "normal-tree",
    name: "Tree",
    category: "tree",
    flags: TileFlag.Impassable | TileFlag.Interactable,
    sprite: "normal-tree",
    width: 1.0,
    height: 1,
    renderHeight: 1.4,
    fallbackColor: 0x2d8a4e,
  },
  "oak-tree": {
    staticId: "oak-tree",
    name: "Oak Tree",
    category: "tree",
    flags: TileFlag.Impassable | TileFlag.Interactable,
    sprite: "oak-tree",
    width: 1.2,
    height: 1,
    renderHeight: 1.6,
    fallbackColor: 0x1b5e30,
  },
  "willow-tree": {
    staticId: "willow-tree",
    name: "Willow Tree",
    category: "tree",
    flags: TileFlag.Impassable | TileFlag.Interactable,
    sprite: "willow-tree",
    width: 1.2,
    height: 1,
    renderHeight: 1.6,
    fallbackColor: 0x3a7d44,
  },
  "cedar-tree": {
    staticId: "cedar-tree",
    name: "Cedar Tree",
    category: "tree",
    flags: TileFlag.Impassable | TileFlag.Interactable,
    sprite: "cedar-tree",
    width: 1.0,
    height: 1,
    renderHeight: 1.5,
    fallbackColor: 0x2e6b3a,
  },
  "cypress-tree": {
    staticId: "cypress-tree",
    name: "Cypress Tree",
    category: "tree",
    flags: TileFlag.Impassable | TileFlag.Interactable,
    sprite: "cypress-tree",
    width: 0.8,
    height: 1,
    renderHeight: 1.8,
    fallbackColor: 0x2a5c34,
  },
  "apple-tree": {
    staticId: "apple-tree",
    name: "Apple Tree",
    category: "tree",
    flags: TileFlag.Impassable | TileFlag.Interactable,
    sprite: "apple-tree",
    width: 1.0,
    height: 1,
    renderHeight: 1.4,
    fallbackColor: 0x4a8a3e,
  },
  "peach-tree": {
    staticId: "peach-tree",
    name: "Peach Tree",
    category: "tree",
    flags: TileFlag.Impassable | TileFlag.Interactable,
    sprite: "peach-tree",
    width: 1.0,
    height: 1,
    renderHeight: 1.4,
    fallbackColor: 0x5a8a3e,
  },
  "banana-tree": {
    staticId: "banana-tree",
    name: "Banana Tree",
    category: "tree",
    flags: TileFlag.Impassable | TileFlag.Interactable,
    sprite: "banana-tree",
    width: 1.0,
    height: 1,
    renderHeight: 1.5,
    fallbackColor: 0x3a7a2e,
  },
  "pine-tree": {
    staticId: "pine-tree",
    name: "Pine Tree",
    category: "tree",
    flags: TileFlag.Impassable | TileFlag.Interactable,
    sprite: "pine-tree",
    width: 0.8,
    height: 1,
    renderHeight: 1.8,
    fallbackColor: 0x1e5a2a,
  },
  "yew-tree": {
    staticId: "yew-tree",
    name: "Yew Tree",
    category: "tree",
    flags: TileFlag.Impassable | TileFlag.Interactable,
    sprite: "yew-tree",
    width: 1.0,
    height: 1,
    renderHeight: 1.5,
    fallbackColor: 0x2a6a30,
  },

  // ---- Rocks & Ores ----
  rock: {
    staticId: "rock",
    name: "Rock",
    category: "rock",
    flags: TileFlag.Impassable | TileFlag.Interactable,
    sprite: "rock",
    width: 0.7,
    height: 1,
    renderHeight: 0.6,
    fallbackColor: 0x808080,
  },
  rocks: {
    staticId: "rocks",
    name: "Rocks",
    category: "rock",
    flags: TileFlag.Impassable | TileFlag.Interactable,
    sprite: "rocks",
    width: 0.9,
    height: 1,
    renderHeight: 0.5,
    fallbackColor: 0x707070,
  },
  boulder: {
    staticId: "boulder",
    name: "Boulder",
    category: "rock",
    flags: TileFlag.Impassable | TileFlag.Interactable,
    sprite: "boulder",
    width: 1.0,
    height: 1,
    renderHeight: 0.8,
    fallbackColor: 0x696969,
  },
  "copper-rock": {
    staticId: "copper-rock",
    name: "Copper Rock",
    category: "rock",
    flags: TileFlag.Impassable | TileFlag.Interactable,
    sprite: "copper-rock",
    width: 0.7,
    height: 1,
    renderHeight: 0.7,
    fallbackColor: 0xc87533,
  },
  "tin-rock": {
    staticId: "tin-rock",
    name: "Tin Rock",
    category: "rock",
    flags: TileFlag.Impassable | TileFlag.Interactable,
    sprite: "tin-rock",
    width: 0.7,
    height: 1,
    renderHeight: 0.7,
    fallbackColor: 0xb0b0b0,
  },
  "iron-rock": {
    staticId: "iron-rock",
    name: "Iron Rock",
    category: "rock",
    flags: TileFlag.Impassable | TileFlag.Interactable,
    sprite: "iron-rock",
    width: 0.7,
    height: 1,
    renderHeight: 0.7,
    fallbackColor: 0x6b3a2a,
  },

  // ---- Structures ----
  anvil: {
    staticId: "anvil",
    name: "Anvil",
    category: "structure",
    flags: TileFlag.Impassable | TileFlag.Interactable | TileFlag.Surface,
    sprite: "anvil",
    width: 0.6,
    height: 1,
    renderHeight: 0.6,
    fallbackColor: 0x555555,
  },
  forge: {
    staticId: "forge",
    name: "Forge",
    category: "structure",
    flags: TileFlag.Impassable | TileFlag.Interactable | TileFlag.Surface,
    sprite: "forge",
    width: 1.0,
    height: 1,
    renderHeight: 1.2,
    fallbackColor: 0xff6633,
  },
  furnace: {
    staticId: "furnace",
    name: "Furnace",
    category: "structure",
    flags: TileFlag.Impassable | TileFlag.Interactable | TileFlag.Surface,
    sprite: "oven",
    width: 1.0,
    height: 1,
    renderHeight: 1.0,
    fallbackColor: 0xcc5533,
  },
  oven: {
    staticId: "oven",
    name: "Oven",
    category: "structure",
    flags: TileFlag.Impassable | TileFlag.Interactable | TileFlag.Surface,
    sprite: "oven",
    width: 1.0,
    height: 1,
    renderHeight: 1.0,
    fallbackColor: 0xcc6644,
  },
  loom: {
    staticId: "loom",
    name: "Loom",
    category: "structure",
    flags: TileFlag.Impassable | TileFlag.Interactable | TileFlag.Surface,
    sprite: "loom",
    width: 1.0,
    height: 1,
    renderHeight: 1.0,
    fallbackColor: 0x8b6914,
  },
  "spinning-wheel": {
    staticId: "spinning-wheel",
    name: "Spinning Wheel",
    category: "structure",
    flags: TileFlag.Impassable | TileFlag.Interactable | TileFlag.Surface,
    sprite: "spinning-wheel",
    width: 0.8,
    height: 1,
    renderHeight: 1.0,
    fallbackColor: 0x8b7355,
  },
  shop: {
    staticId: "shop",
    name: "General Store",
    category: "structure",
    flags: TileFlag.Impassable | TileFlag.Interactable | TileFlag.Surface,
    sprite: "shop",
    width: 1.0,
    height: 1,
    renderHeight: 1.2,
    fallbackColor: 0xcccc33,
  },
  bank: {
    staticId: "bank",
    name: "Bank",
    category: "structure",
    flags: TileFlag.Impassable | TileFlag.Interactable | TileFlag.Surface,
    sprite: "bank",
    width: 1.0,
    height: 1,
    renderHeight: 1.2,
    fallbackColor: 0xdaa520,
  },
  "bank-chest": {
    staticId: "bank-chest",
    name: "Bank Chest",
    category: "structure",
    flags: TileFlag.Impassable | TileFlag.Interactable | TileFlag.Surface,
    sprite: "chest",
    width: 0.8,
    height: 1,
    renderHeight: 0.6,
    fallbackColor: 0xdaa520,
  },
  "cooking-range": {
    staticId: "cooking-range",
    name: "Cooking Range",
    category: "structure",
    flags: TileFlag.Impassable | TileFlag.Interactable | TileFlag.Surface,
    sprite: "cooking-range",
    width: 1.0,
    height: 1,
    renderHeight: 1.2,
    fallbackColor: 0xcc6644,
  },

  // ---- Decorations ----
  barrel: {
    staticId: "barrel",
    name: "Barrel",
    category: "decoration",
    flags: TileFlag.Impassable,
    sprite: "barrel",
    width: 0.5,
    height: 1,
    renderHeight: 0.6,
    fallbackColor: 0x8b6914,
  },
  crate: {
    staticId: "crate",
    name: "Crate",
    category: "decoration",
    flags: TileFlag.Impassable,
    sprite: "crate",
    width: 0.6,
    height: 1,
    renderHeight: 0.5,
    fallbackColor: 0x8b7355,
  },
  chest: {
    staticId: "chest",
    name: "Chest",
    category: "decoration",
    flags: TileFlag.Impassable | TileFlag.Interactable,
    sprite: "chest",
    width: 0.6,
    height: 1,
    renderHeight: 0.5,
    fallbackColor: 0xa08050,
  },
  table: {
    staticId: "table",
    name: "Table",
    category: "decoration",
    flags: TileFlag.Impassable | TileFlag.Surface,
    sprite: "table",
    width: 1.0,
    height: 1,
    renderHeight: 0.5,
    fallbackColor: 0x8b6914,
  },
  chair: {
    staticId: "chair",
    name: "Chair",
    category: "decoration",
    flags: TileFlag.None,
    sprite: "chair",
    width: 0.4,
    height: 1,
    renderHeight: 0.6,
    fallbackColor: 0x8b6914,
  },
  bench: {
    staticId: "bench",
    name: "Bench",
    category: "decoration",
    flags: TileFlag.None,
    sprite: "bench",
    width: 1.0,
    height: 1,
    renderHeight: 0.5,
    fallbackColor: 0x8b6914,
  },
  bookcase: {
    staticId: "bookcase",
    name: "Bookcase",
    category: "decoration",
    flags: TileFlag.Impassable,
    sprite: "bookcase",
    width: 1.0,
    height: 1,
    renderHeight: 1.2,
    fallbackColor: 0x6b4226,
  },
  sign: {
    staticId: "sign",
    name: "Sign",
    category: "decoration",
    flags: TileFlag.Impassable,
    sprite: "sign",
    width: 0.3,
    height: 1,
    renderHeight: 1.0,
    fallbackColor: 0x8b7355,
  },
  "lamp-post": {
    staticId: "lamp-post",
    name: "Lamp Post",
    category: "decoration",
    flags: TileFlag.Impassable,
    sprite: "lamp-post",
    width: 0.3,
    height: 1,
    renderHeight: 1.4,
    fallbackColor: 0xccaa44,
  },
  candelabra: {
    staticId: "candelabra",
    name: "Candelabra",
    category: "decoration",
    flags: TileFlag.Impassable,
    sprite: "candelabra",
    width: 0.3,
    height: 1,
    renderHeight: 1.0,
    fallbackColor: 0xccaa44,
  },

  // ---- Fishing ----
  "fishing-spot": {
    staticId: "fishing-spot",
    name: "Fishing Spot",
    category: "fishing",
    flags: TileFlag.Interactable,
    sprite: "koi-fish",
    width: 0.6,
    height: 1,
    renderHeight: 0.5,
    fallbackColor: 0x5599cc,
  },
  "fishing-spot-shrimp": {
    staticId: "fishing-spot-shrimp",
    name: "Fishing Spot",
    category: "fishing",
    flags: TileFlag.Interactable,
    sprite: "fishing-spot-shrimp",
    width: 0.6,
    height: 1,
    renderHeight: 0.5,
    fallbackColor: 0x5599cc,
  },
  "fishing-spot-trout": {
    staticId: "fishing-spot-trout",
    name: "Fishing Spot (Trout)",
    category: "fishing",
    flags: TileFlag.Interactable,
    sprite: "fishing-spot-trout",
    width: 0.7,
    height: 1,
    renderHeight: 0.6,
    fallbackColor: 0x3377aa,
  },

  // ---- Walls ----
  "stone-wall": {
    staticId: "stone-wall",
    name: "Stone Wall",
    category: "wall",
    flags: TileFlag.Impassable | TileFlag.Wall,
    sprite: "stone-wall",
    width: 1.0,
    height: 1,
    renderHeight: 1.0,
    fallbackColor: 0x888888,
  },
  "wooden-wall": {
    staticId: "wooden-wall",
    name: "Wooden Wall",
    category: "wall",
    flags: TileFlag.Impassable | TileFlag.Wall,
    sprite: "wooden-wall",
    width: 1.0,
    height: 1,
    renderHeight: 1.0,
    fallbackColor: 0x8b7355,
  },

  // ---- Fences ----
  fence: {
    staticId: "fence",
    name: "Fence",
    category: "fence",
    flags: TileFlag.Impassable | TileFlag.Wall,
    sprite: "fence",
    width: 1.0,
    height: 1,
    renderHeight: 0.5,
    fallbackColor: 0x6b5640,
  },
  "wooden-fence": {
    staticId: "wooden-fence",
    name: "Wooden Fence",
    category: "fence",
    flags: TileFlag.Impassable | TileFlag.Wall,
    sprite: "wooden-fence",
    width: 1.0,
    height: 1,
    renderHeight: 0.5,
    fallbackColor: 0x8b7355,
  },
  "stone-fence": {
    staticId: "stone-fence",
    name: "Stone Fence",
    category: "fence",
    flags: TileFlag.Impassable | TileFlag.Wall,
    sprite: "rock",
    width: 1.0,
    height: 1,
    renderHeight: 0.4,
    fallbackColor: 0x888888,
  },
  "iron-fence": {
    staticId: "iron-fence",
    name: "Iron Fence",
    category: "fence",
    flags: TileFlag.Impassable | TileFlag.Wall,
    sprite: "fence",
    width: 1.0,
    height: 1,
    renderHeight: 0.6,
    fallbackColor: 0x555555,
  },
  hedge: {
    staticId: "hedge",
    name: "Hedge",
    category: "fence",
    flags: TileFlag.Impassable | TileFlag.Wall,
    sprite: "normal-tree",
    width: 1.0,
    height: 1,
    renderHeight: 0.5,
    fallbackColor: 0x2d8a4e,
  },
};

export function getStaticTile(staticId: string): StaticTileDef | undefined {
  return STATIC_TILES[staticId];
}
