import type { MonsterDef } from "./types.js";

export const MONSTERS: Record<string, MonsterDef> = {
  chicken: {
    id: "chicken",
    name: "Chicken",
    combatLevel: 1,
    hp: 3,
    attack: 1,
    strength: 1,
    defence: 1,
    alwaysDrops: [
      { itemId: "feathers", quantity: 1 },
      { itemId: "bones", quantity: 1 },
    ],
    loot: [{ itemId: "feathers", weight: 1, minQty: 1, maxQty: 3 }],
  },
  rat: {
    id: "rat",
    name: "Rat",
    combatLevel: 2,
    hp: 5,
    attack: 1,
    strength: 2,
    defence: 1,
    alwaysDrops: [{ itemId: "bones", quantity: 1 }],
    loot: [{ itemId: "rat-tail", weight: 1, minQty: 1, maxQty: 1 }],
  },
  spider: {
    id: "spider",
    name: "Spider",
    combatLevel: 4,
    hp: 8,
    attack: 3,
    strength: 3,
    defence: 2,
    alwaysDrops: [{ itemId: "bones", quantity: 1 }],
    loot: [{ itemId: "spider-silk", weight: 1, minQty: 1, maxQty: 2 }],
  },
  goblin: {
    id: "goblin",
    name: "Goblin",
    combatLevel: 5,
    hp: 12,
    attack: 4,
    strength: 4,
    defence: 3,
    alwaysDrops: [],
    loot: [
      { itemId: "gold", weight: 3, minQty: 5, maxQty: 15 },
      { itemId: "bronze-dagger", weight: 1, minQty: 1, maxQty: 1 },
    ],
  },
  skeleton: {
    id: "skeleton",
    name: "Skeleton",
    combatLevel: 8,
    hp: 18,
    attack: 7,
    strength: 6,
    defence: 5,
    alwaysDrops: [{ itemId: "bones", quantity: 1 }],
    loot: [{ itemId: "iron-dagger", weight: 1, minQty: 1, maxQty: 1 }],
  },
  wolf: {
    id: "wolf",
    name: "Wolf",
    combatLevel: 10,
    hp: 22,
    attack: 8,
    strength: 8,
    defence: 4,
    alwaysDrops: [],
    loot: [
      { itemId: "wolf-pelt", weight: 2, minQty: 1, maxQty: 1 },
      { itemId: "raw-meat", weight: 3, minQty: 1, maxQty: 1 },
    ],
  },
  bandit: {
    id: "bandit",
    name: "Bandit",
    combatLevel: 12,
    hp: 28,
    attack: 10,
    strength: 9,
    defence: 7,
    alwaysDrops: [],
    loot: [
      { itemId: "gold", weight: 3, minQty: 20, maxQty: 50 },
      { itemId: "iron-sword", weight: 1, minQty: 1, maxQty: 1 },
    ],
  },
  "dark-mage": {
    id: "dark-mage",
    name: "Dark Mage",
    combatLevel: 15,
    hp: 32,
    attack: 12,
    strength: 11,
    defence: 6,
    alwaysDrops: [],
    loot: [{ itemId: "gold", weight: 1, minQty: 15, maxQty: 40 }],
  },
  troll: {
    id: "troll",
    name: "Troll",
    combatLevel: 18,
    hp: 45,
    attack: 14,
    strength: 15,
    defence: 12,
    alwaysDrops: [],
    loot: [
      { itemId: "gold", weight: 2, minQty: 50, maxQty: 100 },
      { itemId: "troll-hide", weight: 1, minQty: 1, maxQty: 1 },
    ],
  },
  "briarwood-guardian": {
    id: "briarwood-guardian",
    name: "Briarwood Guardian",
    combatLevel: 20,
    hp: 60,
    attack: 16,
    strength: 18,
    defence: 15,
    alwaysDrops: [],
    loot: [
      { itemId: "gold", weight: 3, minQty: 80, maxQty: 150 },
      { itemId: "guardian-crest", weight: 1, minQty: 1, maxQty: 1 },
    ],
  },
};

export function getMonster(id: string): MonsterDef | undefined {
  return MONSTERS[id];
}
